// src/app/practice/exercises.ts
import type { Exercise } from './types';

export const EXERCISES: Exercise[] = [
  // ─── Breathwork (14) ─────────────────────────────────────────
  {
    id: 'breath-sigh',
    name: 'Physiological Sigh',
    modality: 'breathwork',
    type: 'structured',
    level: 'beginner',
    duration: '1–3 breaths',
    description: 'Double inhale through the nose, long exhale through the mouth. Fastest known calm-down signal.',
    learnMorePath: '/breathe#physio-sigh',
    phases: [
      { label: 'Sniff In', duration: 2 },
      { label: 'Sniff In', duration: 1 },
      { label: 'Exhale', duration: 6 },
    ],
    defaultCycles: 20,
    defaultRounds: 1,
  },
  {
    id: 'breath-box',
    name: 'Box Breathing',
    modality: 'breathwork',
    type: 'structured',
    level: 'beginner',
    duration: '4–10 min',
    description: '4-4-4-4 equal ratio. Used by Navy SEALs for calm under pressure.',
    learnMorePath: '/breathe#box-breathing',
    phases: [
      { label: 'Inhale', duration: 4 },
      { label: 'Hold', duration: 4 },
      { label: 'Exhale', duration: 4 },
      { label: 'Hold', duration: 4 },
    ],
    defaultCycles: 19,
    defaultRounds: 1,
  },
  {
    id: 'breath-478',
    name: '4-7-8 Breathing',
    modality: 'breathwork',
    type: 'structured',
    level: 'beginner',
    duration: '2–5 min',
    description: "Dr. Andrew Weil's calming breath. Activates the vagus nerve.",
    learnMorePath: '/breathe#4-7-8',
    phases: [
      { label: 'Inhale', duration: 4 },
      { label: 'Hold', duration: 7 },
      { label: 'Exhale', duration: 8 },
    ],
    defaultCycles: 16,
    defaultRounds: 1,
  },
  {
    id: 'breath-diaphragm',
    name: 'Diaphragmatic Breathing',
    modality: 'breathwork',
    type: 'reference',
    level: 'beginner',
    duration: '5–15 min',
    description: 'Deep belly breathing that activates the parasympathetic nervous system.',
    learnMorePath: '/breathe#diaphragmatic',
    instructions: [
      'Place one hand on your chest, one on your belly.',
      'Breathe in slowly through the nose — feel your belly rise, chest stays still.',
      'Exhale slowly through the mouth or nose.',
      'Focus on making each exhale slightly longer than the inhale.',
    ],
    defaultMinutes: 10,
  },
  {
    id: 'breath-nadi',
    name: 'Nadi Shodhana',
    modality: 'breathwork',
    type: 'structured',
    level: 'beginner',
    duration: '5–15 min',
    description: 'Alternate nostril breathing. Balances left and right brain hemispheres.',
    learnMorePath: '/breathe#nadi-shodhana',
    phases: [
      { label: 'Left Inhale', duration: 4 },
      { label: 'Hold', duration: 4 },
      { label: 'Right Exhale', duration: 4 },
      { label: 'Right Inhale', duration: 4 },
      { label: 'Hold', duration: 4 },
      { label: 'Left Exhale', duration: 4 },
    ],
    defaultCycles: 12,
    defaultRounds: 1,
  },
  {
    id: 'breath-ujjayi',
    name: 'Ujjayi Breath',
    modality: 'breathwork',
    type: 'reference',
    level: 'beginner',
    duration: '5–20 min',
    description: 'Ocean breath. Slight constriction at the back of the throat creates an audible whisper.',
    learnMorePath: '/breathe#ujjayi',
    instructions: [
      'Sit comfortably. Slightly constrict the back of your throat.',
      'Inhale slowly through the nose — you should hear a soft ocean-like sound.',
      'Exhale through the nose with the same gentle constriction.',
      'Keep the breath smooth, even, and unhurried.',
    ],
    defaultMinutes: 10,
  },
  {
    id: 'breath-coherent',
    name: 'Coherent Breathing',
    modality: 'breathwork',
    type: 'structured',
    level: 'beginner',
    duration: '10–20 min',
    description: '5.5s in, 5.5s out at ~5.5 breaths per minute. Maximizes vagal tone.',
    learnMorePath: '/breathe#coherent',
    phases: [
      { label: 'Inhale', duration: 5.5 },
      { label: 'Exhale', duration: 5.5 },
    ],
    defaultCycles: 60,
    defaultRounds: 1,
  },
  {
    id: 'breath-kapalabhati',
    name: 'Kapalabhati',
    modality: 'breathwork',
    type: 'structured',
    level: 'intermediate',
    duration: '3–10 min',
    description: 'Skull-shining breath. Rapid forceful exhales with passive inhales.',
    learnMorePath: '/breathe#kapalabhati',
    phases: [
      { label: 'Rapid Exhales (30)', duration: 30 },
      { label: 'Rest', duration: 30 },
    ],
    defaultCycles: 3,
    defaultRounds: 1,
  },
  {
    id: 'breath-fire',
    name: 'Breath of Fire',
    modality: 'breathwork',
    type: 'structured',
    level: 'intermediate',
    duration: '3–11 min',
    description: 'Rapid equal inhales and exhales through the nose. Energizing Kundalini technique.',
    learnMorePath: '/breathe#breath-of-fire',
    phases: [
      { label: 'Breath of Fire', duration: 60 },
      { label: 'Hold + Rest', duration: 30 },
    ],
    defaultCycles: 3,
    defaultRounds: 1,
  },
  {
    id: 'breath-wimhof',
    name: 'Wim Hof Method',
    modality: 'breathwork',
    type: 'structured',
    level: 'intermediate',
    duration: '~15 min',
    description: 'Power breathing, breath retention, and recovery. Builds autonomic resilience.',
    learnMorePath: '/breathe#wim-hof',
    phases: [
      { label: 'Power Breathing', duration: 90 },
      { label: 'Breath Hold', duration: 90 },
      { label: 'Recovery Breath', duration: 15 },
    ],
    defaultCycles: 1,
    defaultRounds: 3,
  },
  {
    id: 'breath-buteyko',
    name: 'Buteyko Method',
    modality: 'breathwork',
    type: 'reference',
    level: 'intermediate',
    duration: '10–30 min',
    description: 'Reduced breathing to increase CO₂ tolerance. Nasal breathing focus.',
    learnMorePath: '/breathe#buteyko',
    instructions: [
      'Sit upright. Close your mouth and breathe only through your nose.',
      'Take a normal breath in, then a normal breath out.',
      'Pinch your nose and hold — count seconds until first urge to breathe (Control Pause).',
      'Release and breathe normally. Target: gradually increase your Control Pause.',
    ],
    defaultMinutes: 15,
  },
  {
    id: 'breath-tummo',
    name: 'Tummo',
    modality: 'breathwork',
    type: 'reference',
    level: 'advanced',
    duration: '20–60 min',
    description: 'Tibetan inner fire meditation. Visualization of heat combined with breath retention.',
    learnMorePath: '/breathe#tummo',
    instructions: [
      'Sit in meditation posture. Visualize a thin, hollow central channel from perineum to crown.',
      'Visualize a tiny flame at the navel center.',
      'Inhale deeply, drawing breath down to the flame. Hold with gentle abdominal lock.',
      'Visualize the flame growing with each breath, filling the central channel with heat.',
      'Exhale slowly. Repeat, feeling warmth spread through the body.',
    ],
    defaultMinutes: 20,
  },
  {
    id: 'breath-holotropic',
    name: 'Holotropic Breathwork',
    modality: 'breathwork',
    type: 'reference',
    level: 'advanced',
    duration: '2–3 hours',
    description: 'Accelerated deep breathing with evocative music. Best done in a facilitated group.',
    learnMorePath: '/breathe#holotropic',
    instructions: [
      'This practice should be done with a trained facilitator and a sitter.',
      'Lie down comfortably. Begin breathing faster and deeper than normal.',
      'Maintain connected breathing — no pauses between inhale and exhale.',
      'Allow whatever arises (emotions, movements, sounds) without judgment.',
      'Session lasts 2-3 hours. Integration period follows.',
    ],
    defaultMinutes: 60,
  },
  {
    id: 'breath-cyclic',
    name: 'Cyclic Hyperventilation',
    modality: 'breathwork',
    type: 'structured',
    level: 'intermediate',
    duration: '5–15 min',
    description: 'Huberman Lab protocol. 25 deep breaths followed by breath hold.',
    learnMorePath: '/breathe#cyclic-hyperventilation',
    phases: [
      { label: 'Deep Breaths (25)', duration: 75 },
      { label: 'Hold (exhale)', duration: 30 },
      { label: 'Recovery', duration: 15 },
    ],
    defaultCycles: 3,
    defaultRounds: 1,
  },

  // ─── Meditation (5) ──────────────────────────────────────────
  {
    id: 'med-breath',
    name: 'Breath Awareness',
    modality: 'meditation',
    type: 'reference',
    level: 'beginner',
    duration: '2–20 min',
    description: 'Count exhales 1-10, then restart. The foundation of all meditation.',
    learnMorePath: '/meditate#breath-awareness',
    instructions: [
      'Sit comfortably with eyes closed or softly focused downward.',
      'Breathe naturally. Begin counting each exhale: 1, 2, 3... up to 10.',
      'When you lose count (you will), gently return to 1.',
      'The practice IS the returning — not the counting.',
    ],
    defaultMinutes: 10,
  },
  {
    id: 'med-bodyscan',
    name: 'Body Scan',
    modality: 'meditation',
    type: 'reference',
    level: 'beginner',
    duration: '10–30 min',
    description: 'Systematic attention through each body part. Builds interoceptive awareness.',
    learnMorePath: '/meditate#body-scan',
    instructions: [
      'Lie down or sit comfortably. Close your eyes.',
      'Begin at the top of your head. Notice any sensations without judging.',
      'Slowly move attention down: forehead, eyes, jaw, neck, shoulders...',
      'Continue through arms, hands, chest, belly, hips, legs, feet.',
      'If the mind wanders, gently return to where you left off.',
    ],
    defaultMinutes: 15,
  },
  {
    id: 'med-lovingkindness',
    name: 'Loving-Kindness',
    modality: 'meditation',
    type: 'reference',
    level: 'beginner',
    duration: '10–20 min',
    description: 'Metta meditation. Cultivate compassion for self, loved ones, and all beings.',
    learnMorePath: '/meditate#loving-kindness',
    instructions: [
      'Sit comfortably. Begin with yourself: "May I be happy. May I be healthy. May I be safe."',
      'Expand to a loved one. Visualize them and repeat the phrases.',
      'Expand to a neutral person (someone you neither like nor dislike).',
      'Expand to a difficult person. This is where the practice deepens.',
      'Finally, expand to all beings everywhere.',
    ],
    defaultMinutes: 15,
  },
  {
    id: 'med-visualization',
    name: 'Guided Visualization',
    modality: 'meditation',
    type: 'reference',
    level: 'beginner',
    duration: '10–20 min',
    description: 'Create vivid mental imagery for relaxation, creativity, or intention-setting.',
    learnMorePath: '/meditate#visualization',
    instructions: [
      'Sit or lie down comfortably. Close your eyes.',
      'Choose a scene: a peaceful beach, forest, mountain, or sacred space.',
      'Engage all senses: what do you see, hear, feel, smell?',
      'Spend time in this space. Let it feel real and nurturing.',
      'When ready, slowly return to the room.',
    ],
    defaultMinutes: 15,
  },
  {
    id: 'med-walking',
    name: 'Walking Meditation',
    modality: 'meditation',
    type: 'reference',
    level: 'beginner',
    duration: '10–30 min',
    description: 'Slow, deliberate walking with full attention on each step.',
    learnMorePath: '/meditate#walking-meditation',
    instructions: [
      'Find a quiet path, 10-20 paces long.',
      'Stand at one end. Feel your feet on the ground.',
      'Walk slowly: lift, move, place. Feel each micro-movement.',
      'At the end, pause. Turn slowly. Walk back.',
      'If the mind wanders, notice, then return attention to your feet.',
    ],
    defaultMinutes: 15,
  },

  // ─── Yoga (3) ────────────────────────────────────────────────
  {
    id: 'yoga-hipopening',
    name: 'Hip Opening Sequence',
    modality: 'yoga',
    type: 'structured',
    level: 'beginner',
    duration: '20 min',
    description: '10-step sequence targeting hip flexors, glutes, and deep rotators.',
    learnMorePath: '/yoga#hip-opening',
    phases: [
      { label: 'Constructive Rest', duration: 120 },
      { label: 'Reclined Pigeon (each side)', duration: 120 },
      { label: 'Happy Baby', duration: 90 },
      { label: 'Low Lunge (each side)', duration: 120 },
      { label: 'Lizard (each side)', duration: 120 },
      { label: 'Garland Squat', duration: 90 },
      { label: 'Pigeon (each side)', duration: 180 },
      { label: 'Butterfly', duration: 120 },
      { label: 'Wide-Legged Forward Fold', duration: 90 },
      { label: 'Supine Twist + Savasana', duration: 150 },
    ],
    defaultCycles: 1,
    defaultRounds: 1,
  },
  {
    id: 'yoga-nidra',
    name: 'Yoga Nidra Protocol',
    modality: 'yoga',
    type: 'reference',
    level: 'beginner',
    duration: '20–45 min',
    description: 'Guided sleep meditation through 8 stages. Deep rest without sleeping.',
    learnMorePath: '/yoga#yoga-nidra',
    instructions: [
      'Lie in Savasana. Cover yourself — body temperature drops.',
      'Set your Sankalpa (intention) as a short, positive statement.',
      'Follow the rotation of consciousness through 31-61 body points.',
      'Shift to breath awareness — count breaths backward from 27.',
      'Experience pairs of opposites: heavy/light, hot/cold.',
      'Visualization stage: rapid archetypal images.',
      'Repeat your Sankalpa at the deepest point.',
      'Slowly externalize: wiggle fingers, deepen breath, open eyes.',
    ],
    defaultMinutes: 30,
  },
  {
    id: 'yoga-posehold',
    name: 'Pose Hold Series',
    modality: 'yoga',
    type: 'structured',
    level: 'beginner',
    duration: '6–18 min',
    description: '60-second holds with 10-second transitions. Build strength and presence.',
    learnMorePath: '/yoga#pose-hold',
    phases: [
      { label: 'Hold', duration: 60 },
      { label: 'Transition', duration: 10 },
    ],
    defaultCycles: 5,
    defaultRounds: 1,
  },

  // ─── Fascia (4) ──────────────────────────────────────────────
  {
    id: 'fascia-foamroll',
    name: 'Foam Rolling Protocol',
    modality: 'fascia',
    type: 'structured',
    level: 'beginner',
    duration: '10–20 min',
    description: 'Systematic foam rolling at 1 inch per second, 20-30 seconds per spot.',
    learnMorePath: '/fascia#foam-rolling',
    phases: [
      { label: 'Calves', duration: 60 },
      { label: 'IT Band / Outer Thigh', duration: 60 },
      { label: 'Quads', duration: 60 },
      { label: 'Hamstrings', duration: 60 },
      { label: 'Glutes', duration: 60 },
      { label: 'Upper Back', duration: 60 },
      { label: 'Lats', duration: 60 },
    ],
    defaultCycles: 1,
    defaultRounds: 1,
  },
  {
    id: 'fascia-fitness',
    name: 'Fascial Fitness Morning',
    modality: 'fascia',
    type: 'structured',
    level: 'beginner',
    duration: '10 min',
    description: "Schleip's 4 principles: rehydrate, bounce, stretch, sense. Morning reboot for fascia.",
    learnMorePath: '/fascia#fascial-fitness',
    phases: [
      { label: 'Bouncing / Rebounding', duration: 120 },
      { label: 'Spinal Cat-Cow Waves', duration: 90 },
      { label: 'Fascial Stretches (long holds)', duration: 180 },
      { label: 'Plantar Ball Rolling', duration: 60 },
      { label: 'Self-Sensing / Body Scan', duration: 60 },
    ],
    defaultCycles: 1,
    defaultRounds: 1,
  },
  {
    id: 'fascia-guasha',
    name: 'Self-Gua Sha',
    modality: 'fascia',
    type: 'reference',
    level: 'beginner',
    duration: '5–10 min',
    description: 'Scraping technique to break fascial adhesions and improve circulation.',
    learnMorePath: '/fascia#gua-sha',
    instructions: [
      'Apply oil to the target area (neck, upper back, or forearms).',
      'Use a gua sha tool or smooth edge. Scrape in one direction, 10-15 strokes.',
      'Work from origin to insertion of the muscle.',
      'Redness (sha) is normal — it indicates fascial restriction release.',
      'Drink water afterward. Avoid on broken skin or bruises.',
    ],
    defaultMinutes: 10,
  },
  {
    id: 'fascia-cupping',
    name: 'Self-Cupping',
    modality: 'fascia',
    type: 'reference',
    level: 'intermediate',
    duration: '10–15 min',
    description: 'Myofascial decompression. Lifts tissue to improve glide and circulation.',
    learnMorePath: '/fascia#cupping',
    instructions: [
      'Apply oil to the target area.',
      'Squeeze the silicone cup, place on skin, release to create suction.',
      'Stationary: leave in place 3-5 minutes. Moving: slide slowly along muscle.',
      'Combine with gua sha for compress-then-decompress effect.',
      'Circular marks are normal and fade in 3-7 days. Start with lighter suction.',
    ],
    defaultMinutes: 10,
  },

  // ─── Nervous System (6) ──────────────────────────────────────
  {
    id: 'ns-diaphragm',
    name: 'Slow Diaphragmatic',
    modality: 'nervous-system',
    type: 'reference',
    level: 'beginner',
    duration: '5–10 min',
    description: 'Slow belly breathing at 6 breaths per minute. Direct vagal nerve stimulation.',
    learnMorePath: '/nervous-system#diaphragmatic',
    instructions: [
      'Sit or lie down. Place a hand on your belly.',
      'Inhale slowly through the nose for 5 seconds — belly rises.',
      'Exhale slowly for 5 seconds — belly falls.',
      'Focus on the exhale being slightly longer for maximum parasympathetic activation.',
    ],
    defaultMinutes: 10,
  },
  {
    id: 'ns-gargling',
    name: 'Vagal Gargling',
    modality: 'nervous-system',
    type: 'reference',
    level: 'beginner',
    duration: '1–2 min',
    description: 'Vigorous gargling stimulates the vagus nerve via the pharyngeal muscles.',
    learnMorePath: '/nervous-system#gargling',
    instructions: [
      'Take a large sip of water.',
      'Gargle vigorously for 30 seconds — loud enough to challenge the throat muscles.',
      'Spit out. Repeat 2-3 times.',
      'You may tear up — this is a vagal activation sign.',
    ],
    defaultMinutes: 2,
  },
  {
    id: 'ns-coldface',
    name: 'Cold Face Immersion',
    modality: 'nervous-system',
    type: 'structured',
    level: 'intermediate',
    duration: '30–60 sec',
    description: 'Mammalian dive reflex. Cold water on the face triggers rapid parasympathetic shift.',
    learnMorePath: '/nervous-system#cold-face',
    phases: [{ label: 'Cold Face Immersion', duration: 30 }],
    defaultCycles: 1,
    defaultRounds: 1,
  },
  {
    id: 'ns-coldshower',
    name: 'Cold Shower / Plunge',
    modality: 'nervous-system',
    type: 'structured',
    level: 'intermediate',
    duration: '1–3 min',
    description: 'Cold exposure builds stress resilience and dopamine. Start with 30 seconds.',
    learnMorePath: '/nervous-system#cold-showers',
    phases: [{ label: 'Cold Exposure', duration: 60 }],
    defaultCycles: 1,
    defaultRounds: 1,
  },
  {
    id: 'ns-auricular',
    name: 'Auricular Massage',
    modality: 'nervous-system',
    type: 'reference',
    level: 'beginner',
    duration: '2–5 min',
    description: 'Ear massage targets the auricular branch of the vagus nerve (ABVN).',
    learnMorePath: '/nervous-system#auricular-massage',
    instructions: [
      'Gently massage the outer ear (tragus and concha) between thumb and forefinger.',
      'Apply gentle pressure in circular motions for 2-3 minutes.',
      'Pay special attention to the inner curve of the ear (cymba conchae).',
      'Notice sensations of warmth, tingling, or relaxation.',
    ],
    defaultMinutes: 3,
  },
  {
    id: 'ns-laughter',
    name: 'Laughter Practice',
    modality: 'nervous-system',
    type: 'reference',
    level: 'beginner',
    duration: '5 min',
    description: 'Voluntary laughter becomes real laughter. Diaphragm contracts activate the vagus nerve.',
    learnMorePath: '/nervous-system#laughter',
    instructions: [
      'Stand or sit comfortably.',
      'Begin with forced "ha ha ha" from the belly.',
      'Make eye contact with yourself in a mirror (or others in a group).',
      'Let the absurdity turn forced laughter into genuine laughter.',
      'Continue for 5 minutes. End with deep breathing.',
    ],
    defaultMinutes: 5,
  },

  // ─── Reiki (3) ───────────────────────────────────────────────
  {
    id: 'reiki-self',
    name: 'Self-Reiki Protocol',
    modality: 'reiki',
    type: 'reference',
    level: 'beginner',
    duration: '20–40 min',
    description: '8 hand positions from head to feet. 3-5 minutes per position.',
    learnMorePath: '/reiki#self-reiki',
    instructions: [
      'Position 1 — Eyes/Face: palms cupped over eyes, heels at temples. 3-5 min.',
      'Position 2 — Back of Head: hands under skull, cradling occipital ridge. 3-5 min.',
      'Position 3 — Throat: one hand at base of throat, collarbone level. 3-5 min.',
      'Position 4 — Heart: both hands flat over sternum. 3-5 min.',
      'Position 5 — Solar Plexus: both hands over upper abdomen. 3-5 min.',
      'Position 6 — Lower Abdomen: both hands below navel. 3-5 min.',
      'Position 7 — Knees: one palm on each knee. 3-5 min.',
      'Position 8 — Feet (optional): hands wrapped around soles. 3-5 min.',
    ],
    defaultMinutes: 30,
  },
  {
    id: 'reiki-hatsurei',
    name: 'Hatsurei Ho',
    modality: 'reiki',
    type: 'reference',
    level: 'intermediate',
    duration: '15–20 min',
    description: 'Traditional Japanese Reiki technique. Kenyoku (dry brushing) + Joshin Kokyu Ho (breathing).',
    learnMorePath: '/reiki#hatsurei-ho',
    instructions: [
      'Kenyoku (Dry Brushing): sweep right hand from left shoulder to right hip (3x). Reverse. Then sweep down each arm (3x).',
      'Connect to Reiki: raise hands above head, feel energy flowing down.',
      'Joshin Kokyu Ho: breathe into the hara (lower abdomen). Exhale through hands.',
      'Gassho Meditation: palms together at heart. Focus on the point where middle fingers meet.',
      'Mokunen (Affirm): silently state "I will begin/end Hatsurei Ho."',
    ],
    defaultMinutes: 20,
  },
  {
    id: 'reiki-gassho',
    name: 'Gassho Meditation',
    modality: 'reiki',
    type: 'reference',
    level: 'beginner',
    duration: '10–20 min',
    description: 'Hands in prayer position at heart. Focus on the point where middle fingertips meet.',
    learnMorePath: '/reiki#gassho',
    instructions: [
      'Sit comfortably. Bring palms together at heart center.',
      'Close your eyes. Focus all attention on the point where your middle fingertips meet.',
      'When thoughts arise, gently return focus to the fingertips.',
      "Maintain for 10-20 minutes. This is Usui's core meditation practice.",
    ],
    defaultMinutes: 15,
  },

  // ─── Sound Healing (3) ───────────────────────────────────────
  {
    id: 'sound-bhramari',
    name: 'Bhramari (Bee Breath)',
    modality: 'sound-healing',
    type: 'structured',
    level: 'beginner',
    duration: '5 min',
    description: 'Humming breath. The vibration stimulates the vagus nerve and calms the mind.',
    learnMorePath: '/sound-healing#bhramari',
    phases: [
      { label: 'Inhale', duration: 4 },
      { label: 'Hum (exhale)', duration: 8 },
    ],
    defaultCycles: 10,
    defaultRounds: 1,
  },
  {
    id: 'sound-om',
    name: 'Om / So Hum Chanting',
    modality: 'sound-healing',
    type: 'reference',
    level: 'beginner',
    duration: '5–15 min',
    description: 'Chest-resonant chanting at your natural pitch. Vagal stimulation through vibration.',
    learnMorePath: '/sound-healing#chanting',
    instructions: [
      'Sit upright. Take a deep breath in.',
      'Chant "Om" or "So Hum" at a pitch that resonates in your chest.',
      'Sustain the sound for the full exhale — feel vibration in sternum and throat.',
      'Inhale naturally. Repeat. Find a rhythm that feels meditative.',
    ],
    defaultMinutes: 10,
  },
  {
    id: 'sound-bath',
    name: 'Sound Bath Listening',
    modality: 'sound-healing',
    type: 'reference',
    level: 'beginner',
    duration: '15–30 min',
    description: 'Lie down and receive sound from singing bowls, gongs, or a recorded bath.',
    learnMorePath: '/sound-healing#sound-bath',
    instructions: [
      'Lie in Savasana in a quiet, dark room.',
      'Play a sound bath recording (singing bowls, gongs, or crystal bowls).',
      'Close your eyes. Let the sound wash over you without analyzing.',
      'If thoughts arise, return attention to the sound vibrations.',
      'Remain still for a few minutes after the sound ends.',
    ],
    defaultMinutes: 20,
  },

  // ─── Somatics (5) ────────────────────────────────────────────
  {
    id: 'soma-tre',
    name: 'TRE Wall Sit Protocol',
    modality: 'somatics',
    type: 'structured',
    level: 'beginner',
    duration: '20–30 min',
    description: '7 exercises to fatigue the psoas, then allow neurogenic tremoring in butterfly position.',
    learnMorePath: '/somatics#tre',
    phases: [
      { label: 'Ankle Stretches', duration: 60 },
      { label: 'Calf Raises', duration: 60 },
      { label: 'Forward Fold Hang', duration: 120 },
      { label: 'Wall Sit (thighs parallel)', duration: 120 },
      { label: 'Wall Sit (deeper)', duration: 60 },
      { label: 'Standing Hip Opener', duration: 60 },
      { label: 'Butterfly Supine — Allow Tremoring', duration: 600 },
    ],
    defaultCycles: 1,
    defaultRounds: 1,
  },
  {
    id: 'soma-constructive',
    name: 'Constructive Rest',
    modality: 'somatics',
    type: 'reference',
    level: 'beginner',
    duration: '15 min',
    description: 'Alexander Technique floor practice. Knees bent, head on books. Spinal decompression.',
    learnMorePath: '/somatics#constructive-rest',
    instructions: [
      'Lie on your back on a firm surface.',
      'Place 1-3 paperback books under your head (not a pillow).',
      'Bend your knees, feet flat on the floor hip-width apart.',
      'Rest hands on your lower ribs or beside you.',
      'Think: "Let my neck be free, let my head go forward and up, let my back lengthen and widen."',
      'Do nothing. Let gravity decompress. Stay for 15 minutes.',
    ],
    defaultMinutes: 15,
  },
  {
    id: 'soma-voo',
    name: 'The Voo Sound',
    modality: 'somatics',
    type: 'reference',
    level: 'beginner',
    duration: '3–5 min',
    description: "Peter Levine's low-pitched \"Voooo\" on exhale. Settles the viscera via vagal activation.",
    learnMorePath: '/somatics#voo-sound',
    instructions: [
      'Sit or stand. Take a deep breath in.',
      'On the exhale, make a deep, low "Vooooooo" sound.',
      'Pitch it as low as you comfortably can — feel it vibrate in your belly.',
      'At the end of the exhale, pause and notice internal sensations.',
      'Repeat 5-10 times.',
    ],
    defaultMinutes: 5,
  },
  {
    id: 'soma-orienting',
    name: 'Orienting Exercise',
    modality: 'somatics',
    type: 'reference',
    level: 'beginner',
    duration: '2–3 min',
    description: 'Slow head/eye sweep around the room. Tells the nervous system the environment is safe.',
    learnMorePath: '/somatics#orienting',
    instructions: [
      'Sit comfortably. Slowly turn your head to the right.',
      'Let your eyes look at what your head is turning toward — take it in.',
      'Pause when something catches your attention. Really see it.',
      'Continue the slow sweep all the way to the left.',
      'Notice any sighs, yawns, or settling — signs of discharge.',
    ],
    defaultMinutes: 3,
  },
  {
    id: 'soma-containment',
    name: 'Containment',
    modality: 'somatics',
    type: 'reference',
    level: 'beginner',
    duration: '5 min',
    description: 'Self-holding with hands on chest and belly. Names physical sensations to build awareness.',
    learnMorePath: '/somatics#containment',
    instructions: [
      'Place one hand on your chest and one on your belly.',
      'Feel the warmth of your hands through your clothing.',
      'Name what you notice physically: "I feel pressure... warmth... tightness..."',
      "Stay with sensations. Don't try to change them.",
      'Breathe naturally. Let the containment create safety.',
    ],
    defaultMinutes: 5,
  },

  // ── Sleep ─────────────────────────────────────────────────────
  {
    id: 'evening-4-7-8',
    name: 'Evening 4-7-8 Breathing',
    modality: 'sleep',
    type: 'structured',
    level: 'beginner',
    duration: '2–5 min',
    description: 'Extended exhale pattern that maximally engages the vagal brake. The 2:1 exhale-to-inhale ratio shifts the autonomic nervous system toward parasympathetic dominance.',
    learnMorePath: '/sleep#breathwork',
    phases: [
      { label: 'Inhale', duration: 4 },
      { label: 'Hold', duration: 7 },
      { label: 'Exhale', duration: 8 },
    ],
    defaultCycles: 4,
    defaultRounds: 1,
    defaultMinutes: 5,
  },
  {
    id: 'pre-sleep-yoga-nidra',
    name: 'Pre-Sleep Yoga Nidra',
    modality: 'sleep',
    type: 'reference',
    level: 'beginner',
    duration: '20 min',
    description: 'Systematic rotation of consciousness that induces theta and delta brain waves while maintaining awareness. The bridge between waking practice and sleep.',
    learnMorePath: '/sleep#yoga-nidra',
    defaultMinutes: 20,
    instructions: [
      'Lie down in savasana (corpse pose). Close your eyes.',
      'Set your sankalpa — a short, positive intention stated mentally three times.',
      'Rotate awareness through each body part: right hand thumb, index finger, middle finger... following the guided sequence.',
      'Count breaths backward from 27 to 1. If you lose count, start again from 27.',
      'Experience opposite sensations: heavy/light, warm/cool.',
      'If sleep comes during the practice, welcome it — this is the ideal outcome.',
    ],
  },
  {
    id: 'wind-down-body-scan',
    name: 'Wind-Down Body Scan',
    modality: 'sleep',
    type: 'reference',
    level: 'beginner',
    duration: '15 min',
    description: 'Interoceptive awareness practice that activates the insular cortex — the same circuit the brain uses to assess internal safety. Supports the neuroception of safety required for sleep.',
    learnMorePath: '/sleep#wind-down',
    defaultMinutes: 15,
    instructions: [
      'Lie in bed in a comfortable position. Close your eyes.',
      'Begin at the crown of your head. Notice any sensation without trying to change it.',
      'Slowly move awareness down: forehead, eyes, jaw (release tension here), throat, shoulders.',
      'Continue through arms, hands, chest, belly (let the breath move here naturally).',
      'Move through hips, legs, feet. Spend extra time on areas holding tension.',
      'Expand awareness to the whole body as a single field of sensation.',
      'Rest in this whole-body awareness. Let sleep come when it comes.',
    ],
  },
  {
    id: 'cyclic-sighing',
    name: 'Cyclic Sighing',
    modality: 'sleep',
    type: 'structured',
    level: 'beginner',
    duration: '5 min',
    description: 'Double nasal inhale followed by extended mouth exhale. The 2023 Stanford RCT found 5 minutes more effective than mindfulness meditation for reducing anxiety.',
    learnMorePath: '/sleep#breathwork',
    phases: [
      { label: 'Double inhale', duration: 3 },
      { label: 'Long exhale', duration: 7 },
    ],
    defaultCycles: 30,
    defaultRounds: 1,
    defaultMinutes: 5,
  },
  {
    id: 'sleep-coherence',
    name: 'Sleep Coherence Breathing',
    modality: 'sleep',
    type: 'structured',
    level: 'beginner',
    duration: '10 min',
    description: 'Breathing at the resonance frequency of the cardiovascular system (~5.5 bpm). Maximizes HRV and primes the autonomic nervous system for the parasympathetic dominance of deep sleep.',
    learnMorePath: '/sleep#breathwork',
    phases: [
      { label: 'Inhale', duration: 5.5 },
      { label: 'Exhale', duration: 5.5 },
    ],
    defaultCycles: 55,
    defaultRounds: 1,
    defaultMinutes: 10,
  },

  // ── Qigong ────────────────────────────────────────────────────
  {
    id: 'ba-duan-jin',
    name: 'Ba Duan Jin (Eight Brocades)',
    modality: 'qigong',
    type: 'reference',
    level: 'beginner',
    duration: '12–15 min',
    description: 'The most researched qigong form. Eight standing movements targeting the whole body — spine, shoulders, hips, legs, and internal organs. Takes 12-15 minutes for a complete round.',
    learnMorePath: '/qigong#forms',
    defaultMinutes: 15,
    instructions: [
      'Stand with feet shoulder-width apart, knees slightly bent, arms relaxed.',
      'Move through each of the eight movements slowly, coordinating breath with motion.',
      'Inhale during expansion/rising movements. Exhale during contraction/sinking.',
      'Repeat each movement 6-8 times before transitioning to the next.',
      'Maintain soft focus and relaxed shoulders throughout.',
      'End with 1-2 minutes of still standing, hands at lower abdomen.',
    ],
  },
  {
    id: 'zhan-zhuang',
    name: 'Zhan Zhuang (Standing Meditation)',
    modality: 'qigong',
    type: 'reference',
    level: 'beginner',
    duration: '10–20 min',
    description: 'Stand like a tree — the internal counterpart to moving qigong. Isometric muscle engagement meets meditative stillness. Builds deep parasympathetic states while strengthening legs and core.',
    learnMorePath: '/qigong#forms',
    defaultMinutes: 15,
    instructions: [
      'Stand with feet shoulder-width apart, knees slightly bent (never locked).',
      'Raise arms as if holding a large ball at chest height. Elbows below shoulders, fingers pointing toward each other.',
      'Relax shoulders down. Tuck chin slightly. Breathe slowly through the nose.',
      'When legs tremble or burn, breathe into the sensation rather than fighting it.',
      'Start with 5 minutes. Add 1-2 minutes per week as comfort allows.',
      'End by slowly lowering arms and standing still for 30 seconds.',
    ],
  },
  {
    id: 'wu-qin-xi',
    name: 'Five Animal Frolics (Wu Qin Xi)',
    modality: 'qigong',
    type: 'reference',
    level: 'intermediate',
    duration: '20–25 min',
    description: 'Imitate the movements of tiger, deer, bear, monkey, and crane. Each animal cultivates a different quality — from power and grounding to agility and lightness.',
    learnMorePath: '/qigong#forms',
    defaultMinutes: 20,
    instructions: [
      'Begin with 2-3 minutes of gentle warm-up movement.',
      'Tiger: Strong, gripping movements emphasizing bone and tendon strength.',
      'Deer: Graceful turns and stretches for spinal flexibility.',
      'Bear: Heavy, grounded swaying for stability and digestive function.',
      'Monkey: Quick, playful movements for agility and mental sharpness.',
      'Crane: Balanced, light movements for poise and respiratory function.',
      'Perform each animal sequence for 3-4 minutes before transitioning.',
    ],
  },
  {
    id: 'liu-zi-jue',
    name: 'Six Healing Sounds (Liu Zi Jue)',
    modality: 'qigong',
    type: 'structured',
    level: 'beginner',
    duration: '10–15 min',
    description: 'Six exhalation sounds each directed at a specific organ system. The extended exhale activates the vagus nerve while vibrations stimulate vagal afferents in the throat — similar to Bhramari humming.',
    learnMorePath: '/qigong#forms',
    defaultMinutes: 10,
    phases: [
      { label: 'Xu (Liver)', duration: 10 },
      { label: 'He (Heart)', duration: 10 },
      { label: 'Hu (Spleen)', duration: 10 },
      { label: 'Si (Lungs)', duration: 10 },
      { label: 'Chui (Kidneys)', duration: 10 },
      { label: 'Xi (Triple Burner)', duration: 10 },
    ],
    defaultCycles: 6,
    defaultRounds: 1,
  },
];
